### ISSUE TITLE
Several UI windows need pagination, e.g., uploaded datasets

### ISSUE THREAD

**Issue by ArtPoon** [cfe-lab/Kive#380]
This is especially problematic when dealing with lists with many entries.

**Comment by jnak-cfe** [comment]
Question about this:
Could we just implement pagination in the frontend? Would be a less complicated, however, it would get sort of unwieldy if our sets start getting into the thousands.

**Comment by donkirkby** [comment]
The API already supports pagination with a couple of lines of boilerplate. See the page where you choose input datasets for an example of the needed API changes.

**Comment by ArtPoon** [comment]
For example of search interface, see Analysis page in User portal.

**Comment by ArtPoon** [comment]
Description field in Dataset browser UI is not wrapping to table column width.

**Comment by rhliang** [comment]
Note: this is going to be harder to implement on pages such as the Methods page or the CodeResourceRevisions pages, because those are implemented as child views on the Method and CodeResource ViewSets respectively.  A possible solution is to instead implement these pages' API calls as filtered queries on Method and CodeResourceRevision respectively.

**Comment by rhliang** [comment]
Note that I'm punting on the more difficult cases referred to in issue #441.
