### ISSUE TITLE
Cannot upload binary file as CodeResource

### ISSUE THREAD

**Issue by ArtPoon** [cfe-lab/Kive#403]
Trying to load bowtie2 index files that contain human genome references for a revision of mixed-hcv pipeline on Bulbasaur Kive.  Apparently the file upload is blocked.

**Comment by rhliang** [comment]
The problem was that the specific binary file used had a plus symbol in the filename.  On backend validation, this produced a ValidationError, but it wasn't being properly unpacked on the frontend so no error was visibly reported.  The workaround, for now, is to make sure uploaded files are proper slugs when you upload them.  Note that the name of the file that you upload must be slugified, as changing the resource name on submission isn't enough.

I'll open another issue for that.

**Comment by rhliang** [comment]
Sorry -- they don't necessarily have to be slugs, they have to obey this regex: `^(\b|([-_.()\w]+ *)*[-_.()\w]+)$`
