### ISSUE TITLE
mpi4py issues

### ISSUE THREAD

**Issue by jjh13** [cfe-lab/Kive#425]
I'm on a new machine, and I've gotten Kive mostly working, however, I'm having issues with the mpi4py module and getting the workers up. I've installed via macports 
```
port install py27-mpi4py
sudo port select --set mpi mpich-mp-fortran
```
but when I try to spin up workers I get
```
Macintosh:kive joshua$ ./manage.py runfleet -w5
[mpiexec@Macintosh.local] match_arg (utils/args/args.c:159): unrecognized argument pmi_args
[mpiexec@Macintosh.local] HYDU_parse_array (utils/args/args.c:174): argument matching returned error
[mpiexec@Macintosh.local] parse_args (ui/mpich/utils.c:1596): error parsing input array
[mpiexec@Macintosh.local] HYD_uii_mpx_get_parameters (ui/mpich/utils.c:1648): unable to parse user arguments
[mpiexec@Macintosh.local] main (ui/mpich/mpiexec.c:153): error parsing parameters
```
I'm sure I've just overlooked some small setup config, anyone know what I missed?

**Comment by donkirkby** [comment]
I would check that you set up `hostfile`, and check which version of MPI you are running. I am running Open MPI 1.6.5. Your stack trace makes it look like you might be running MPICH instead of Open MPI, and I think there were problems with MPICH.

Another thing to try is to run a much simpler MPI program as a test. I posted one [as a gist][mpi], and there are a couple of others there.

[mpi]: https://gist.github.com/donkirkby/be2d583d0eb53daf82f7

**Comment by jjh13** [comment]
Okay, this was definitely because of MPICH. I cleaned my environment and installed OpenMPI, then mpi4py via pip

```
port install openmpi-gcc49
pip install mpi4py
```

and everything works. Installing via `port install py27-mpi4py` caused problems because by default it depends on MPICH.
