### ISSUE TITLE
Multiple published pipelines allowed?

### ISSUE THREAD

**Issue by jnak-cfe** [cfe-lab/Kive#430]
While fixing #429, I discovered another problem. The backend seems to allow multiple published versions.
Am I remembering this wrong? I thought only 1 published version of a pipeline is allowed?

**Comment by donkirkby** [comment]
Pipelines are now allowed to have more than one published version. That changed in the last release or two, because it wasn't clear what to do when the published version is not visible to the same users that the pipeline family is visible to. Issue #369 is related to the change, but there may have been an earlier issue as well.
