### ISSUE TITLE
Should we make "add new CodeResourceRevision to CodeResource" and "create new CodeResource" more distinct?

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#456]
We already did this for Method (see #398) and Pipeline (in the code leading to #369).  Under this scheme, one would be able to:
- create a new CodeResource, with an initial CodeResourceRevision
- revise an existing CodeResourceRevision
- add a new CodeResourceRevision to an existing CodeResource

**Comment by ArtPoon** [comment]
To clarify, we are asking for an "add new" button under the "revise a code resource" template to create a CR object that is not linked to a previous CR.

This issue was raised by the existence of two distinct types of `aln2counts.py` scripts that have divergent functions and inputs/outputs.  Can this be made more visible to the user by presenting the branching diagram of this CR's revision history?
