### ISSUE TITLE
PostgreSQL throws OperationalError on the cluster

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#487]
Getting this error message:

```
  File "/usr/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
OperationalError: FATAL:  connection limit exceeded for non-superusers
```

Looks like now that we have batching in place, we're hitting the database too much.  We should dig and see if this is something that can be configured on PostgreSQL.

**Comment by rhliang** [comment]
Yes it can be configured, and we did do that on the cluster.  I'll dig up how we did it and add it to the docs.

**Comment by donkirkby** [comment]
This happened again, so I increased the limit to 300 connections. PostgreSQL refused to shut down for the restart, so we may be leaving connections open somehow.

To force the shut down without waiting for connections to close, I ran this:

    sudo su - postgres
    /usr/bin/pg_ctl stop -m fast
    /usr/bin/pg_ctl start

I also stopped and started Apache, since it has connections to the database. I'm not sure if that was necessary.
