### ISSUE TITLE
Clicking output cable moves output icon

### ISSUE THREAD

**Issue by ArtPoon** [cfe-lab/Kive#503]
Unexpected behaviour.  I don't know whether this was intended as a feature.

**Comment by donkirkby** [comment]
Just to clarify, this is only for output cables. Clicking input cables disconnects the cable and drags it around.

Should clicking the output cable do nothing?

**Comment by jnak-cfe** [comment]
This was a decision we made a long time ago. (I think you were there, Art!)
I have never been that crazy about it. It would probably be more consistent with our model if you could disconnect outputs and just have dismembered outputs bobbing about (although you wouldn't be able to commit a pipeline like this).

**Comment by donkirkby** [comment]
To summarize the discussion so far, we have three options for what happens when you click an output cable:

1. drag the output icon (the current situation)
2. disconnect the cable from the output icon (consistent with input cables)
3. nothing

Are there any other options? My personal preference is for number three, because I can't see any reason the user would *want* number two.

**Comment by ArtPoon** [comment]
Group consensus is for option 2.
