### ISSUE TITLE
Failed integrity/content checks on data should not retroactively invalidate all previous Runs using that data

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#545]
At the moment, if a Dataset is corrupted, it retroactively goes through and marks all of the Runs that used that Dataset as unsuccessful.  This works OK for the time being but it doesn't allow for data to be later recovered.  Moreover, it's maybe not sensible to allow a Run to be retroactively failed; rather, the Run should probably remain successful, but the UI should emphasize to the user that particular Datasets created by it are suspect.

Especially with the fact we're soon going to be supporting external files, this has become important.

**Comment by ArtPoon** [comment]
Three options for handling scenarios where a data set (file) has been corrupted and may have since been repaired (this applies to integrity checks):
1. As soon as we see a corrupted file, we marked it as such and treat it that way in the future indefinitely.
2. Optimistically use datasets even if they failed in the past and attempt to run again; if the pipeline fails because of a corrupt data set, we are able to go back and check its content (update the same Run object).
3. Have a manual recheck - run is treated as failed forever, but there is a link that lets you recheck the contents and reprocess the run as another instance of a Run object.

We are inclined towards option 2.

**Comment by rhliang** [comment]
This was fixed as part of issue #515 (which is still ongoing).
