### ISSUE TITLE
Page size appears to change when changing columns

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#590]
Steps to reproduce:

1. Produce enough data to fill the selector enough to require multiple pages (in my case, more than 5 datasets)
2. Choose a dataset for the first input

Expected behaviour:
selector moves to second column, showing the same number of datasets per page

Actual behaviour:
selector moves to second column, showing 7 datasets per page now

**Comment by rhliang** [comment]
Also, when I added another row and choose an input for the first column, it now shows me 6 datasets per page.

**Comment by jamesnakagawa** [comment]
Number of rows is calculated based on: 

* The green button's top edge
* The search table's top edge + the search table's height

The following elements are shown/hidden/animated using asynchronous functions:

* `above_box` which contains the entire search dialog
* The search table which morphs based on search results/pagination
* The green button which tracks with `above_box`'s bottom edge as well as the input it pertains to

This issue is probably because the # of rows calculation is taking place before all the animations have completed. I have tried to account for above_box and the search table, but the green button animation might be screwing it up and producing variable results.

**Comment by donkirkby** [comment]
See if this is a reasonably easy fix -- if it's too much, scrap worrying about this and implement an infinite scroll system instead.

**Comment by jamesnakagawa** [comment]
The green button animating is the culprit — now just have to figure out how to insert the animation callback function.

**Comment by jamesnakagawa** [comment]
This ended up being because the _width_ of the green button was not initially set, so the text flow wrapped upwards and caused it to be _tall_.
