### ISSUE TITLE
Integrity violation crashed the fleet

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#618]
The fleet crashed after an integrity violation. It looks like the timing was just right to put a run step into quarantine before it went through the `worker_finished()` method. That caused an [assertion](https://github.com/cfe-lab/Kive/blob/v0.8.4/kive/fleet/workers.py#L592) to fail and crash the fleet.

**Comment by donkirkby** [comment]
It looks like this is caused by issue #569, but crashing the fleet is a new problem caused by the quarantine changes in version 0.8. If we can't fix #569 yet, we have to at least stop it from crashing the fleet.

**Comment by rhliang** [comment]
Just had another crash that looks like it was caused by this.  Curiously, after stopping all of the active runs that showed a quarantined step, without starting the fleet back up, all of their status strings went back to showing that the quarantined step was a normal successful step.  However if you looked at their view_results pages, they still showed errors.

**Comment by rhliang** [comment]
Note to self: look through the code in the Slurm execution branch(es) and find the defensive code added for such purposes, and add the commit hash to this issue for reference and possible backporting.

**Comment by rhliang** [comment]
The commits which contain the new defensive code in the Slurm branch are 6e0663a324047a6b15aecbc3ae1f18917f7fc97d and 4a50b40305cd6a4628d2bf0a086cba674ece22d1.
