### ISSUE TITLE
kive demo - no version control of samtools

### ISSUE THREAD

**Issue by ArtPoon** [cfe-lab/Kive#642]
I was unable to run the micall demo because my version of samtools is too new (1.3.1) and they've changed the invocation for `samtools sort`.  Actually I think I will take advantage of this and make a second version of the pipeline to reflect this.  Logging this issue anyhow.

**Comment by donkirkby** [comment]
What version of the micall demo are you using, @ArtPoon? The version in the demo fixture doesn't use samtools anymore.

**Comment by ArtPoon** [comment]
That's strange, I had nuked the database so whatever fixtures I loaded came from the demo as of release RC6

**Comment by donkirkby** [comment]
I see you're right, @ArtPoon. The latest release, 0.8.5, still uses samtools in the demo. Scotty regenerated the demo fixture early in the 0.9 milestone to use more recent MiCall code.

You should be able to use the `master` branch, I don't know of any big issues with it. Otherwise, you could probably copy the demo fixture from master onto the 0.8.5 release. Let us know if you run into trouble with that.

**Comment by ArtPoon** [comment]
Thanks @donkirkby -- it ended up being a moot point because I was unable to spin up a worker fleet right before the lecture, so I instead gave a very GUI-intensive demo with no pipeline execution.  Will post as a separate issue.
