### ISSUE TITLE
Implement docker support for methods in pipelines

### ISSUE THREAD

**Issue by wrpscott** [cfe-lab/Kive#681]
In order to decouple the execution environment of a pipeline method from the underlying host OS, every method should run in a docker image.
A default docker image will be provided to help with the transition.

* [x] Run all pipelines in a default docker image.
* [x] Run docker without granting root access to Kive fleet user.
* [x] Kive must keep track of available docker images (users must be able to add docker images)
* [x] During pipeline construction, the user must be able to select a docker for a method, and the versioning of a method must be coupled to a specific docker image.
* [x] Add methods to removal plan when removing a docker image.
* [x] Make method driver optional, and just use the docker image's default entry point when there is no driver.
* [x] Use image hash when launching docker?
* [ ] Add docker images to pipeline dump and upload.

**Comment by donkirkby** [comment]
Suggested features to use for reducing required access when running Docker containers:

* Run docker as a [non-root user] by adding the kivefleet user to the docker group.
* Map the container's root user to a non-root host user with [user namespaces].
* Either require that all outputs are globally readable, or run `chmod` in another docker command after the method finishes.

[non-root user]: https://docs.docker.com/engine/installation/linux/linux-postinstall/
[user namespaces]: https://docs.docker.com/engine/security/userns-remap/

**Comment by donkirkby** [comment]
I've added the `fleet/docker_wrap.py` script as a helper script that can load input files into a docker container, run a command in the container, then copy the output files. Right now, it's useful for limited user accounts to run docker images without needing full access to docker.

Next step is to convert the Kive sandbox code to use this script instead of mounting the sandbox folder directly in the docker container. @rhliang suggested starting with the `finish_cable()` method.

**Comment by rhliang** [comment]
Huh, I thought I left a comment on this before but I guess I didn't.  Just wanted to advise also that `Pipeline.run_cable()` is another place to look.  In fact you'd probably do well to look at all usages of the `copy_and_confirm` and `confirm_file_copy` methods in `file_access_utils.py`.
